# Auth Service Ingress (REST)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "2"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"

    cert-manager.io/cluster-issuer: letsencrypt-prod



spec:
  tls:
    - hosts:
        - 68.233.107.28.nip.io
      secretName: pagepulse-tls
  rules:
    - host: 68.233.107.28.nip.io
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 3000

# Book Service Ingress (REST)
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/limit-rps: "60"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"

    cert-manager.io/cluster-issuer: letsencrypt-prod


spec:
  tls:
    - hosts:
        - 68.233.107.28.nip.io
      secretName: pagepulse-tls
  rules:
    - host: 68.233.107.28.nip.io
      http:
        paths:
          - path: /api/books(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: book-service
                port:
                  number: 3000

# Chat Service Ingress (REST)
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/limit-rps: "60"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "4"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

    cert-manager.io/cluster-issuer: letsencrypt-prod


spec:
  tls:
    - hosts:
        - 68.233.107.28.nip.io
      secretName: pagepulse-tls
  rules:
    - host: 68.233.107.28.nip.io
      http:
        paths:
          - path: /api/chat(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: chat-service
                port:
                  number: 3000

# Notification Service Ingress (REST)
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/limit-rps: "30"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"

    cert-manager.io/cluster-issuer: letsencrypt-prod


spec:
  tls:
    - hosts:
        - 68.233.107.28.nip.io
      secretName: pagepulse-tls
  rules:
    - host: 68.233.107.28.nip.io
      http:
        paths:
          - path: /api/notification(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notification-service
                port:
                  number: 3000

# Chat Socket Ingress (WebSocket - No Rewrite)
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-socket-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  tls:
    - hosts:
        - 68.233.107.28.nip.io
      secretName: pagepulse-tls
  rules:
    - host: 68.233.107.28.nip.io
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: chat-service
                port:
                  number: 3000
