apiVersion: v1
kind: ConfigMap
metadata:
  name: pagepulse-config
data:
  POSTGRES_USER: "admin"
  POSTGRES_DB: "pagepulse_db"
  RABBITMQ_DEFAULT_USER: "guest"
  HTTP_PORT: "3000"
  GRPC_PORT_AUTH: "50051"
  GRPC_PORT_BOOK: "50051"
