apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
        env:
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: pagepulse-secrets
              key: RABBITMQ_URL
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: pagepulse-config
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: pagepulse-config
              key: SMTP_PORT
        - name: SMTP_USER
          valueFrom:
            configMapKeyRef:
              name: pagepulse-config
              key: SMTP_USER
        - name: SMTP_PASS
          valueFrom:
            configMapKeyRef:
              name: pagepulse-config
              key: SMTP_PASS
        - name: PUBLIC_URL
          valueFrom:
            configMapKeyRef:
               name: pagepulse-config
               key: PUBLIC_URL
