apiVersion: v1
kind: Secret
metadata:
  name: pagepulse-secrets
type: Opaque
stringData:

  # PostgreSQL
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "your_postgres_password"
  POSTGRES_CHAT_USER: "chat_admin"
  POSTGRES_CHAT_PASSWORD: "your_chat_postgres_password"
  DB_URL: "postgres://admin:your_postgres_password@postgres-service:5432/pagepulse_db"
  DB_URL_CHAT: "postgres://chat_admin:your_chat_postgres_password@postgres-chat-service:5432/chat_db"

  # RabbitMQ
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "your_rabbitmq_password"
  RABBITMQ_URL: "amqp://guest:your_rabbitmq_password@rabbitmq-service:5672"

  # MongoDB (Notification)
  MONGODB_USER: "admin"
  MONGODB_PASSWORD: "your_mongodb_password"
  MONGODB_DB: "karanraj3056_db_user"
  MONGODB_URL: "your_mongodb_connection_url"

  # Auth / Security
  JWT_SECRET: "your_jwt_secret"

  # Email (SMTP)
  SMTP_USER: "your_email@gmail.com"
  SMTP_PASS: "your_smtp_password"

  # AWS S3
  AWS_ACCESS_KEY_ID: "your_aws_access_key"
  AWS_SECRET_ACCESS_KEY: "your_aws_secret_key"
  S3_BUCKET_NAME: "your_bucket_name"
